import slugify from '../utils/slugify'

export default {
  title: "Journal",
  name: 'journal',
  type: "document",
  fields: [
    {
      title: "Title",
      description: "The name of this journal entry",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Post Date",
      description: "Press the button to the right to pick a date.",
      name: "date",
      type: "date",
      options: {
        dateFormat: "MMMM Do YYYY",
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'Image',
      description: "The supporting image for this journal entry",
      name: 'image',
      type: 'defaultImage',
      validation: Rule => Rule.required()
    },
    {
      title: 'Content',
      description: "The content text for this journal entry",
      name: 'content',
      type: 'text',
      rows: 6,
      validation: Rule => Rule.required()
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          let titleSlug = ''
          let campaignSlug = ''
          if (doc.title) {
            titleSlug = `${doc.title}`
          } else {
            titleSlug = ''
          }

          if (doc.campaignTitle) {
            campaignSlug = `-${doc.campaignTitle}`
          } else {
            campaignSlug = ''
          }

          return `${titleSlug}${campaignSlug}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    }
  ],
  preview: {
    select: {
      title: 'title',
      image: 'image',
      date: 'date',
    },
    prepare(selection) {
      const {title, image, date} = selection
      return {
        title: title,
        subtitle: `${date}`,
        media: image
      }
    }
  }
}